# utils/config.py

import os
from woocommerce import API
from dotenv import load_dotenv
load_dotenv()  # โหลดจาก .env



CODE = os.getenv("CODE")
GOOGLE_SHEET_ID = os.getenv("GOOGLE_SHEET_ID")
# ของ shopee
SHOPEE_PARTNER_ID = os.getenv("SHOPEE_PARTNER_ID")
SHOPEE_PARTNER_SECRET = os.getenv("SHOPEE_PARTNER_SECRET")
SHOPEE_PARTNER_KEY = os.getenv("SHOPEE_PARTNER_KEY")
SHOPEE_SHOP_ID = os.getenv("SHOPEE_SHOP_ID")
SHOPEE_ACCESS_TOKEN = os.getenv("SHOPEE_ACCESS_TOKEN")
SHOPEE_REDIRECT_URI = os.getenv("SHOPEE_REDIRECT_URI")
SS_SHOP_ID = os.getenv("SS_SHOP_ID")
 # ของ เว็บไซต์ fujikathailand.com
FUJIKA_WP_USER = os.getenv("FUJIKA_WP_USER")
FUJIKA_WP_PASSWORD = os.getenv("FUJIKA_WP_PASSWORD")
FUJIKA_WP_APP_PASSWORD_API_ACCESS = os.getenv("FUJIKA_WP_APP_PASSWORD_API_ACCESS")
WOOCOMMERCE_URL = os.getenv("WOOCOMMERCE_URL")
WOOCOMMERCE_CONSUMER_KEY = os.getenv("WOOCOMMERCE_CONSUMER_KEY")
WOOCOMMERCE_CONSUMER_SECRET = os.getenv("WOOCOMMERCE_CONSUMER_SECRET")  
SERVICE_AC = os.getenv("SERVICE_AC")
SERVICE_AC_SHP = os.getenv("SERVICE_AC_SHP")
GOOGLE_SHEET_ID = os.getenv("GOOGLE_SHEET_ID")
# 🛠️ Fujikaservice.com (บริการหลังการขาย)
FUJIKA_SERVICE_SITE_URL = os.getenv("FUJIKA_SERVICE_SITE_URL")
FUJIKA_SERVICE_CONSUMER_KEY = os.getenv("FUJIKA_SERVICE_CONSUMER_KEY")
FUJIKA_SERVICE_CONSUMER_SECRET = os.getenv("FUJIKA_SERVICE_CONSUMER_SECRET")

#lazada
LAZADA_CLIENT_ID = os.getenv("LAZADA_CLIENT_ID")
LAZADA_APP_ID = os.getenv("LAZADA_APP_ID")
LAZADA_CLIENT_SECRET = os.getenv("LAZADA_CLIENT_SECRET")
LAZADA_APP_SECRET = os.getenv("LAZADA_CLIENT_SECRET")
LAZADA_REDIRECT_URI = os.getenv("LAZADA_REDIRECT_URI")
#facebook
FB_ACCESS_TOKEN = os.getenv("FB_ACCESS_TOKEN")
FB_PAGE_ID = os.getenv("FB_PAGE_ID")
FACEBOOK_APP_ID = os.getenv("FACEBOOK_APP_ID")
FACEBOOK_PAGE_IDS = os.getenv("FACEBOOK_PAGE_IDS")
FACEBOOK_PAGE_ID_ONE = os.getenv("FACEBOOK_PAGE_ID_ONE")
FACEBOOK_PAGE_ID_TWO = os.getenv("FACEBOOK_PAGE_ID_TWO")
FACEBOOK_APP_SECRET = os.getenv("FACEBOOK_APP_SECRET")
FACEBOOK_PAGE_HEATER_ID = os.getenv("FACEBOOK_PAGE_HEATER_ID")
FACEBOOK_PAGE_BBQ_ID = os.getenv("FACEBOOK_PAGE_BBQ_ID")

#line
LLINE_CHANNEL_ID = os.getenv("LINE_CHANNEL_ID")
LINE_CHANNEL_SECRET = os.getenv("LINE_CHANNEL_SECRET")
#fujikaservice
FUJIKA_SERVICE_API_KEY = os.getenv("FUJIKA_SERVICE_API_KEY")
#cps
CPS_WP_USER = os.getenv("CPS_WP_USER")
CPS_WP_APP_PASSWORD_API_ACCESS = os.getenv("CPS_WP_APP_PASSWORD_API_ACCESS")

SECRET_KEY = os.getenv("SECRET_KEY")